Azure/AzOps

- src/Comments.md
> updating PR message for oof sync message

- .gitignore
- src/Comments.md
- src/private/Get-AzOpsResourceDefinitionAtScope.ps1
> changing Write-Ouput to Write-AzOpsLog

- entrypoint.ps1
Importing of the Write-AzOpsLog function within the GitHub Action
> Add AzOpsLog dot source

- .azure-pipelines/ubuntu-latest.yml
> updating CI path to include template directory

- action.yml
- entrypoint.ps1
Adding support for environment variables.
#22
> adding enviornment variables

- template/template.json
> updated managementGroup API version

- template/tenant.json
managementGroups and managementGroups/subscriptions + enabling subscription move in template
> updating API version for managementGroups

- src/private/Invoke-AzOpsGitPushRefresh.ps1
- src/public/Invoke-AzOpsGitPull.ps1
- src/public/Invoke-AzOpsGitPush.ps1
- Remove unnecessary params
- Remove test code
> Environment Variables

- README.md
- src/public/Invoke-AzOpsGitPull.ps1
- Fix upstream forking issue
- Minor text change
> Fork Workflow Issue

- src/private/Get-AzOpsResourceDefinitionAtScope.ps1
- template/template.json
- template/tenant.json
> BugFix for RoleAssignment Error for Deny policies

- src/public/Initialize-AzOpsGlobalVariables.ps1
Fixes #32 - related to PowerShell strict mode
> Bugfix for Discovery with "Tenant Root Goup" only is failing

- README.md
> Link implementation guide to the article in CAF

- .azure-pipelines/ubuntu-latest.yml
> Ignoring markdown files

- Dockerfile
- Suppress module installation progress
> Preference Logging

- template/auxiliary/activityLog.json
- template/auxiliary/monitoring.json
- template/enterprise-scale-arm-template.json
- template/esux.json
- template/tenant.json
- template/ux-foundation.json
- template/ux-vwan.json
- updated e2e template to optionally move subscription and do policy assignment + resource deployment
- new folder + templates (auxiliary)
- uiDefinition for curated deployment experience in portal (esux.json)
> Template update

- template/tenant.json
> adding deployment().location

- src/private/Remove-AzOpsDeployments.ps1
> adding function to remove deployments

- Dockerfile
- src/AzOps.psd1
- tests/AzOps.Module.Tests.ps1
Revised release version for AzOps within the repository.
> Release version

- template/tenant.json
- tests/AzOps.Module.Tests.ps1
> BugFix - Enabling Subscription Move

- schema/2020-08-01/azstate.json
Minor bug with the schema $id link
> Fix Schema Id

- .github/workflows/release.yml
> Add support for Publishing docker container

- .github/workflows/release.yml
- action.yml
> Feature - Action to use docker image

- .github/workflows/branch.yml
- .github/workflows/release.yml
- Remove whitespace in module version
> Refactor release workflow

- .github/workflows/branch.yml
> Remove module whitespace

- .github/workflows/branch.yml
> Rename image label

- src/private/Test-AzOpsRuntime.ps1
Minor error message update to match registry key name.
> Update error message

- README.md
Fix the README issue badge status
> Update badge status

- entrypoint.ps1
- src/AzOps.psm1
- src/private/Get-AzOpsResourceDefinitionAtScope.ps1
- src/private/Save-AzOpsManagementGroupChildren.ps1
- Updated entrypoint with correct variable names
- Fixes issue with error handling in scenarios with stale subscriptions returned by the management group api
> Updated fix to handle stale subscriptions

- action.yml
- src/private/Start-AzOpsNativeExecution.ps1
> Fix ShouldProcess Issue

- src/private/Test-AzOpsRuntime.ps1
- Fixes #82 
- Added additional error output with link to remediation instructions in enterprise-scale repo
> updated logic and added check for git longpath setting

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
> Fix issue labels

- src/public/Initialize-AzOpsGlobalVariables.ps1
- Exclusion of unwanted subscription states in discovery
> Exclusion of unwanted subscription states in discovery

- src/public/Initialize-AzOpsGlobalVariables.ps1
Update exclusion of certain subscription patterns
> Update exclusion of subscription

- src/private/ConvertTo-AzOpsState.ps1
Fix global variables - generalize templates and export raw templates
> Fix global variables - generalize templates and export raw templates

- src/private/Get-AzOpsResourceDefinitionAtScope.ps1
Fix missing runspace generalize templates variable
> Fix generalize templates variable

- src/AzOpsStateConfig.json
Add ResourceGroupName and SubscriptionId exclusions in StateConfig
> Fix ResourceGroupName and SubscriptionId exlusion in StateConfig

- src/Comments.md
- src/public/Invoke-AzOpsGitPush.ps1
> Updating Consistency Check Text

- src/public/Initialize-AzOpsGlobalVariables.ps1
> Enabling Opt-out for Auto merge

- src/public/Invoke-AzOpsGitPull.ps1
> Adding -R option for gh pr merge to point to local fork

- src/public/Invoke-AzOpsGitPull.ps1
Reset system branch to main for AzOps Pull
> Reset system branch to main for AzOps Pull

- tests/AzOps.IAB.Tests.ps1
Add clean up block for in-a-box tests
> Enabling Clean up of IAB

- action.yml
- src/public/Invoke-AzOpsGitPull.ps1
Fix auto-merge bug where the Pull Request isn't quite ready to merge.
> Fix auto-merge delay

- src/public/Invoke-AzOpsGitPull.ps1
> BugFix - adding error handling when auto merging system branch

- src/public/Invoke-AzOpsGitPush.ps1
Relax pull requirements before push to optimise performance in large environment
> Relax pull requirements before push to optimise performance in large environment

- src/public/Invoke-AzOpsGitPush.ps1
> BugFix - Feature relax strict mode

- README.md
Fix Azure Pipelines status badge in README.md
> Fix Azure Pipelines badge

- src/private/Invoke-AzOpsChange.ps1
> bug fix for case sensitive effectiveResourceType

- src/public/Invoke-AzOpsGitPush.ps1
Fix strict mode bug with undefined $Skip variable
> Fix uninitialized variable

- src/public/Initialize-AzOpsRepository.ps1
**This PR fixes** minor logging message error.
> Update logging message

- src/public/Invoke-AzOpsGitPush.ps1
Disable system commit after Push workflow has completed.
> Disable System Commit for Azure DevOps

- support.md
> adding support.md

- template/20-create-child-managementgroup.parameters.json
- template/template.json
Disabling scoped deployment for child management group due to validation API error.
> BugFix - Disabling scoped deployment for child management group due to validation API error

- template/template.json
> Bugfix- removing output for policyref

- src/functions/Initialize-AzOpsEnvironment.ps1
- src/internal/functions/Get-AzOpsManagementGroups.ps1
- src/localized/en-us/strings.psd1
> adding support for principals without / permissions

- scripts/Install.ps1
- src/functions/Initialize-AzOpsRepository.ps1
Revert Install.ps1 changes to PSF branch state
Add build folder
Fix couple minor casing issue
> Build Support and Install Script

- build/ado-build.ps1
> Build Script

- src/functions/Initialize-AzOpsRepository.ps1
- Add SkipPolicy configuration item
- Add SkipResourceGroup configuration item
- Add SkipRole configuration item
> Skip Configurations

- .github/workflows/release.yml
- .github/workflows/validate.yml
- scripts/Validate.ps1
- Add workflow for Testing
- Add workflow for Releases
- Fix Validation path
> Workflows for Testing and Releases

- src/functions/Initialize-AzOpsEnvironment.ps1
- src/functions/Initialize-AzOpsRepository.ps1
- src/localized/en-us/Strings.psd1
Enable dynamic discovery of management groups unless PartialMgDiscovery/PartialMgDiscoveryRoot explicitly has been provided.
> Enable dynamic discovery of partial root

- scripts/Release.ps1
- Add module dependencies handlers within the release scripts
> Scripts (Release) - Module Dependencies

- src/internal/functions/ConvertTo-AzOpsState.ps1
> Bugfix for empty parameter files for management group and policy definitions

- src/internal/classes/AzOpsScope.ps1
- src/internal/functions/Invoke-AzOpsChange.ps1
BugFix for Template and parameter lookup
> BugFix for Template and parameter lookup

- src/internal/functions/New-AzOpsDeployment.ps1
- Switch to logging errors for template deployment issues
> Deployment Logging

- src/internal/functions/New-AzOpsDeployment.ps1
- Switch to the `DeploymentWhatIfResult` cmdlets
> Template Validation

- src/internal/functions/New-AzOpsDeployment.ps1
- Modify if conditions to check for errors
> Template Deployment - Error Conditions

- src/data/template/Microsoft.Management/managementGroups/subscriptions.template.jq
- src/internal/functions/ConvertTo-AzOpsState.ps1
- src/localized/en-us/Strings.psd1
- Add subscriptions template
- Refactor Subscription type handling
- Update logging messages
> Subscriptions Template

- action.yml
- Add `action.yml` for migration support
> Migration - Action

- src/data/template/template.jq
- Set default ordering of tags on the resource object
> Tags - Sorting

- .pipelines/sync.yml
Add `sync.yml` for Azure Pipelines configuration
> Azure Pipelines - Sync

- .github/workflows/test.yml
- Add path filtering to the tests trigger
> Tests - Filtering

- .pipelines/release.ps1
> Azure Pipelines - Release

- .pipelines/release.yml
- Update the default behavior of publishing
> Azure Pipelines

- .gitignore
- src/internal/configurations/Core.ps1
- Update the default directory to 'root' replacing 'azops'
> Default Directory

- scripts/Debug.ps1
- src/internal/functions/Get-AzOpsResourceDefinition.ps1
- src/internal/functions/Save-AzOpsManagementGroupChildren.ps1
- src/localized/en-us/Strings.psd1
- Add condition for Subscriptions which aren't in active state.
> Fix: Unable to find Subscription

- src/AzOps.psd1
- src/internal/classes/AzOpsScope.ps1
- src/internal/functions/New-AzOpsScope.ps1
BugFix for State Path Validator
> BugFix for State Path Validator 

- src/AzOps.psd1
- Fix pinning of module dependency versions within manifest
> Module Dependency

- src/AzOps.psd1
- Increment PSFramework version
> Dependencies - PSFramework 

- src/AzOps.psd1
- Increment PSFramework version within module manifest - [Changelog](https://github.com/PowershellFrameworkCollective/psframework/blob/development/PSFramework/changelog.md)
> Dependencies - PSFramework

- src/AzOps.psd1
- Increment dependency version for Az.Accounts
> Dependencies - Az modules

- .gitattributes
- Set default line endings for jq files to `LF`
> Line Endings

- src/AzOps.psd1
> Release Notes

- .github/workflows/release.yml
- scripts/Release.ps1
- scripts/Version.ps1
- New release workflow
- Trigger `workflow_dispatch` with release type
- Auto increment module version
- Create release with tag
> Release Automation

- .github/workflows/dependencies.yml
- Better support for forked repositories
> Dependencies

- src/internal/classes/AzOpsScope.ps1
- src/internal/functions/Invoke-AzOpsChange.ps1
- src/internal/functions/New-AzOpsDeployment.ps1
- src/localized/en-us/Strings.psd1
- Fix Regex lookups for Subscriptions and Resources
- Remove blank spaces
- Fix logging message
- Add handler for Resource Types
- Add handler for duplicate Deployments
> Deployments

- src/internal/functions/Invoke-AzOpsChange.ps1
- src/internal/functions/New-AzOpsDeployment.ps1
- src/localized/en-us/Strings.psd1
- Add validation support into the deployment functions
> Validation

- src/functions/Initialize-AzOpsRepository.ps1
> Removing AzADUser output

- docs/wiki/Introduction.md
Did a few small language adjustments to make the Introduction page in the Wiki a little easier to read.
I understand that this might be an unsolicited contribution and if you don't feel that it is helpful, don't hesitate to just reject it.
> Few small language adjustements

- docs/wiki/Prerequisites.md
> Adjustment of ARM_CLIENT_SECRET output

- src/data/template/Microsoft.KeyVault/vaults.template.jq
- src/data/template/Microsoft.Resources/resourceGroups.template.jq
- src/internal/functions/Set-AzOpsWhatIfOutput.ps1
- Updated jq templates for resourceGroups and vaults to include and order tags
Closing #402
> Ordering of resourceGroup tags

- .github/PULL_REQUEST_TEMPALTE.md
This PR adds a PR template (uniform with all ESLZ repos).
> Add PR Template

- src/data/template/Microsoft.Authorization/policyAssignments.template.jq
- src/data/template/Microsoft.Authorization/policyDefinitions.template.jq
- src/data/template/Microsoft.Authorization/policyExemptions.template.jq
- src/data/template/Microsoft.Authorization/policySetDefinitions.template.jq
- src/data/template/Microsoft.Authorization/roleAssignments.template.jq
- src/data/template/Microsoft.Authorization/roleDefinitions.template.jq
- src/data/template/Microsoft.KeyVault/vaults.template.jq
- src/data/template/Microsoft.Management/managementGroups.template.jq
- src/data/template/Microsoft.Management/managementGroups/subscriptions.template.jq
- src/data/template/Microsoft.Resources/resourceGroups.template.jq
- src/data/template/template.jq
- src/internal/functions/ConvertTo-AzOpsState.ps1
This Pull Request is for merging the Metadata Enhancements to AzOps. 
1. Adds - Metadata to the AzOps pull templates
1. N/A
This feature has been tested and verified.
> Added powershell version to Metadata of Template

- src/data/template/template.json
Remove reference to private repo in template.json
> Remove reference to private repo in template.json

- src/internal/functions/Set-AzOpsWhatIfOutput.ps1
Closing #434 
Updated json serialization depth for whatif output to fix #434
> Changed json serialization depth for whatif output

- docs/wiki/Prerequisites.md
Update to prerequisites, switch to ms graph commands from azuread modules.
This closes #382 
N/A
N/A
N/A
- [ x ] Checked for duplicate [Pull Requests](https://github.com/Azure/azops/pulls)
- [ x ] Associated it with relevant [issues](https://github.com/Azure/azops/issues), for tracking and closure.
- [ x ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/azops/tree/main)
- [ x ] Performed testing and provided evidence.
- [ x ] Updated relevant and associated documentation.
> Wiki update prerequisites

- .github/workflows/dependencies.yml
- scripts/UpdateRequiredModules.ps1
Enhance module version updates from a issue automation behavior to code update and pr.
1. Changed logic in dependencies pipeline
2. Moved some inline code to script file
N/A
Tested in separate repo:
> Dependencies version

- docs/wiki/GitHub-OIDC.md
> Fix broken link in wiki

- README.md
- docs/wiki/AzOps-Contribution.md
Fixed typos in docs.
1. Fixed typo in README.md
2. Fixed typo in AzOps-Contribution.md
> Fixed typos in readme and contribution guide

- docs/wiki/Prerequisites.md
> Update prereq with ps7

- docs/wiki/GitHub-OIDC.md
Removed preview-specific code/notes as the feature is now GA.
> Github OIDC integration GA update

- .github/workflows/tests.yml
> Move secrets to specific environment

- .github/workflows/tests.yml
> Revert OIDC test

- src/tests/integration/Repository.Tests.ps1
Adding integration tests for AzOps-Push.
> Added integration tests for AzOps-Push 

- scripts/ARMAzOpsSetup.ps1
Moving script to MS-managed repo to address https://github.com/Azure/Enterprise-Scale/issues/912
> Add GitHub bootstrap script for Portal deployment experience

- docs/wiki/Self-Hosted.md
- docs/wiki/_Sidebar.md
Fixes #548 and possibly also #569
Added a wiki article with guidance on using self-hosted agents/runners.
1. New wiki article `self-hosted.md`
2. Added link to sidebar
N/A
N/A
> Added wiki article with guidance for running self-hosted agents/runners

- src/functions/Invoke-AzOpsPush.ps1
Added escape character to resolve #600
1. Fixes #600
N/A
> Added escape character to fix issue #600

- .github/workflows/tests.yml
- scripts/New-AzOpsTestsDeploymentHelper.ps1
- src/functions/Initialize-AzOpsEnvironment.ps1
- src/tests/Pester.ps1
- src/tests/functional/Functional.Tests.ps1
- src/tests/functional/Microsoft.Authorization/policyAssignments/scenario.ps1
- src/tests/functional/Microsoft.Authorization/roleAssignments/scenario.ps1
- src/tests/functional/Microsoft.KeyVault/vaults/scenario.ps1
- src/tests/functional/Microsoft.Management/managementGroups/scenario.ps1
- src/tests/functional/Microsoft.Network/azureFirewalls/scenario.ps1
- src/tests/functional/Microsoft.Network/networkInterfaces/scenario.ps1
- src/tests/functional/Microsoft.Network/networkSecurityGroups/scenario.ps1
- src/tests/functional/Microsoft.Network/publicIPAddresses/scenario.ps1
- src/tests/functional/Microsoft.Network/routeTables/scenario.ps1
- src/tests/functional/Microsoft.Network/virtualNetworks/scenario.ps1
- src/tests/functional/Microsoft.Resources/resourceGroups/scenario.ps1
- src/tests/functional/Microsoft.Storage/storageAccounts/scenario.ps1
- src/tests/functional/Microsoft.Web/serverfarms/scenario.ps1
- src/tests/functional/Microsoft.Web/sites/scenario.ps1
- src/tests/functional/README.md
- src/tests/integration/Repository.Tests.ps1
Updates Functional Tests Flow by separating the Pester execution and avoiding unnecessary nesting and lowers logging verbosity to cleanup testing output.
1. Changes .github/workflows/tests.yml
2. Changes src/tests/Pester.ps1
3. Changes src/tests/functional/Functional.Tests.ps1
4. Changes a reference in all scenario.ps1 files
5. Changes src/tests/functional/README.md
6. Changes src/tests/integration/Repository.Tests.ps1
N/A
This has been tested in fork to ensure GitHub Actions succeed and fail in the desired way.
> FunctionalTestsFlowUpdate

- scripts/ARMAzOpsSetup.ps1
Add retry to handle eventual consistency of the public keys for a newly created repository. 
Closing #672 
1. Closing #672 
N/A
Tested end-to-end deployment of new repository with successful results
> Add retry for GItHub public key in bootstrap script

- docs/wiki/_Sidebar.md
Link has moved from the previous source.
Replaces the old link (deploy-enterprise-scale) with the new one (Deploying-ALZ).
> fix link to Deployments chapter

- docs/wiki/Azure-Pipelines.md
Change from relative to static link (same as in GitHub Actions page)
> Fix prerequisities link

- src/internal/functions/New-AzOpsDeployment.ps1
- src/internal/functions/Remove-AzOpsDeployment.ps1
- src/internal/functions/Set-AzOpsWhatIfOutput.ps1
This PR changes the headlines of the WhatIf deploys.
If a result is given, the headline will be the scope(s) in which that specific block will change.
If a file has no changes it will output that filename instead.
fixes #716 
none
> Fix headlines for WhatIf output

- docs/wiki/Steps.md
Added brief documentation of redeploy pipeline added in https://github.com/Azure/AzOps-Accelerator/pull/126
> Add redeploy documentation

- docs/wiki/GitHub-Actions.md
- docs/wiki/GitHub-OIDC.md
- docs/wiki/Prerequisites.md
Updated documentation to reflect pipeline changes for federated credentials (https://github.com/Azure/AzOps-Accelerator/pull/133).
1. Closing #743 
N/A
Validated new pipelines as part of https://github.com/Azure/AzOps-Accelerator/pull/133
> Updated documentation for GitHub/Azure AD federated credentials 

- .github/workflows/release.yml
Removing pull request creation/merge from release pipeline as per latest GitHub org level changes. Pull request will have to be created manually post-release to update module manifest post-release moving forward. 
Tested in other repo, branch will successfully be created with current settings.
> Update release pipeline 

- docs/wiki/Azure-Pipelines.md
This PR updates incorrect link in Azure Pipeline markdown file.
1. Changes `Azure-Pipelines.md`
N/A
Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).
> fixing broken link

- src/AzOps.psd1
> Release 2.1.2

- .github/workflows/tests.yml
Change checkout reference from github.event.pull_request.head.ref to github.event.pull_request.head.sha
Validated in my own repo
> Update test checkout reference

- .github/workflows/release.yml
Update release workflow with permissions to comply with latest changes from the organization
> Update permissions on release workflow

- .github/workflows/wiki-sync.yml
Update wiki-sync workflow with permissions to comply with latest changes from the organization
> Update permissions on wiki-sync workflow

- .github/workflows/wiki-sync.yml
Update Documentation workflow with added manual trigger.
> Update Documentation workflow trigger
