- src/public/Initialize-AzOpsGlobalVariables.ps1
Removes duplicate timestamp logging, AzOpsLog includes timestamp at the start of the output.
_VERBOSE: [2020-07-17 10:45:08.1945] (Initialize-AzOpsGlobalVariables) Global Variable AzOpsState or AzOpsAzManagementGroup is not Initialized. Initializing it now 07/17/2020 11:45:08_
_VERBOSE: [2020-07-17 10:45:08.1945] (Initialize-AzOpsGlobalVariables) Global Variable AzOpsState or AzOpsAzManagementGroup is not Initialized. Initializing it now_
> Removed duplicate timestamps

- .azure-pipelines/ubuntu-latest.yml
- Dockerfile
- src/AzOps.psd1
- src/AzOps.psm1
- src/private/ConvertTo-AzOpsState.ps1
- src/private/Get-AzOpsAllSubscription.ps1
- src/public/Initialize-AzOpsGlobalVariables.ps1
- New Az PowerShell target versions in codebase, tests and action
- Az.Accounts **(1.9.1)**
- Az.Resources **(2.3.0)**
- Switched from Get-AzSubscription to Invoke-AzRestMethod for subscription discovery to be able to filter on subscription QuotaId
> Updated Az target version, Subscription exclusion through QuotaID

- src/private/Get-AzOpsAllSubscription.ps1
Adding paging support to retrieve subscriptions in tenant
> Adding paging support to retrieve subscription greater than 50 in a tenant

- src/public/Invoke-AzOpsGitPush.ps1
Adding logging to ensure filenames are logged when deploying template
> adding logging to ensure filenames are logged

- src/public/Initialize-AzOpsGlobalVariables.ps1
- src/public/Initialize-AzOpsRepository.ps1
- Automatic discovery of partial root management groups based on RBAC permissions.
Closing #132
> [Feature] Added support for dynamic mg root discovery

- src/private/Get-AzOpsAllSubscription.ps1
- src/public/Initialize-AzOpsGlobalVariables.ps1
Added logic to handle subscriptions and throw a warning instead of a terminating error for subscriptions that are in PastDue state (issues with billing). (https://docs.microsoft.com/en-us/rest/api/resources/subscriptions/list#subscriptionstate)
> Handle subscriptions in PastDue state

- src/private/Get-AzOpsAllManagementGroup.ps1
- src/private/Get-AzOpsResourceDefinitionAtScope.ps1
- src/public/Initialize-AzOpsGlobalVariables.ps1
Feature - Disabling properties bag creation in ```<managementgroup>.json``` and ```<subscription>.json```  to avoid duplication
Breaking change
- ```<managementgroup>.json``` and ```<subscription>.json``` will only have immediate child instead of  (n) depth of management group and subscriptions. This will ensure when leaf node changes (add/delete/move), it will not trigger change all the up to the root
-  properties bag in <managementgroup>.json and <subscription>.json is removed to ensure all artefacts are represented only once in repo (avoiding duplication of  ARM templates and reducing the file length). This will ensure each resource have its own lifecycle in Git and can be managed independently.
> Feature - Disabling properties bag creation in <managementgroup>.json and <subscription>.json to avoid duplication

- src/AzOps.psd1
- src/internal/classes/AzOpsScope.ps1
- src/internal/functions/New-AzOpsScope.ps1
- src/localized/en-us/Strings.psd1
Priority - Normal (BAU).
Removing duplicate code in switch statement due to bug
Scenario:  Empty file with .json is checked in repo/
Behaviour:  Empty fie is not valid JSON file. Empty Json should've minimum file content '{}'. However, due to bug that is combination of Get-Content and ConvertFrom-Json when empty file with .json (that is valid file but not valid Json), switch statement is failing to handle $null value unless assigned explicitly.
> [Enhancement] Removing duplicate code in switch statement

- .github/workflows/dependencies.yml
New workflow which runs on a schedule (every six hours), that will check for new PowerShell modules within PSGallery.
If an updated version is detected, the workflow will raise an issue, label it and notify the EnterpriseScale vTeam for review.
---
> Dependencies Automation

- docs/wiki/GitHub-Actions.md
Added missing steps to the Scripts section in the GitHub-Actions.md wiki.
- Added steps on how to disable *Allow Merge commits* and *Allow rebase merging* on the repo using GitHub CLI
- Changed the format from `/repos/:owner/:repo` to `/repos/{owner}/{repo}`. Easier to understand and follows the GitHub CLI docs.
> Added steps to disable rebase merging and merge commits to wiki

- src/internal/functions/New-AzOpsDeployment.ps1
- src/internal/functions/Set-AzOpsWhatIfOutput.ps1
- src/localized/en-us/Strings.psd1
Introduced a new function to output both MD and JSON files
> What-If to output raw Json

- src/functions/Invoke-AzOpsPush.ps1
Process changes in AzOps when git status for files are R of less than 100 value (eg. R099 and below). 
Closing #397 
N/A
> Process files on git rename status with copy score 

- src/internal/functions/Set-AzOpsContext.ps1
Changed WhatIf preference to $false for Set-AzContext to ensure subscription context can be changed in validate step when Invoke-AzOpsPush is called with the -WhatIf switch.
Closing #410 
N/A
> WhatIf preference for Set-AzContext

- src/internal/classes/AzOpsScope.ps1
- src/internal/functions/New-AzOpsDeployment.ps1
Closing #418 and #396
1.  Changed so policySetDefinitions generate parameter files instead of regular deployment templates to overcome escaping issues (#418)
2. Improved WhatIf/Validate error handling to throw terminating errors on template errors (#396)
> Changed generation of policySetDefinitions and improved whatif error handling 

- src/functions/Initialize-AzOpsEnvironment.ps1
Closing #422. 
Added -ListAvailable switch to Get-AzResourceProvider cmdlet to ensure all resourceproviders are enumerated regardless of registration status.
> Fix to enumerate resourceProviders that are not registered in current context

- src/AzOps.psd1
- src/data/template/Microsoft.Authorization/policyDefinitions.jq
- src/data/template/Microsoft.Authorization/policySetDefinitions.jq
Closing #413, #414 and #415
1. #414
2. #413
3. Changed jq template for policyDefinitions and policySetDefinitions to include relevant metadata (#415) 
Metadata returned:
> Metadata for policyDefinitons/policySetdefinitions and update of dependencies 

- docs/wiki/Settings.md
- src/internal/configurations/Core.ps1
- src/internal/functions/Get-AzOpsResourceDefinition.ps1
Adds the capability to exclude/skip resource types at rg scope that should not or cant be synced.
By default it excludes/skips: 'Microsoft.VSOnline/plans','Microsoft.PowerPlatform/accounts','Microsoft.PowerPlatform/enterprisePolicies'
1. closing #427
2. adds new setting called "SkipResourceType"
N/A
Tested that declared resource types are excluded from workflows.
> SkipResourceType

- src/internal/functions/Set-AzOpsWhatIfOutput.ps1
Updated WhatIfOutput information attached to comments during PR Validate Action. Makes information provided easier to read. related #417 
1. Changed Set-AzOpsWhatIfOutput.ps1 output from full json to standard WhatIf output.
2. Added parameter for result size and set default value to 64.000 (Github limit 65.000)
N/A
Testing performed:
> WhatIfOutput

- scripts/Dependencies.ps1
- src/tests/Pester.ps1
- src/tests/integration/Repository.Tests.ps1
- src/tests/templates/azuredeploy.jsonc
To increase confidence in changes to the codebase this PR adds additional automated tests to validate three pull operations:
1. Policy assignment at management group scope
2. Role assignment at subscription scope
3. Resource deployment at resource group scope
1. Adds deployment of a policy assignment
2. Adds deployment of a role assignment
3. Adds deployment of a resource deployment
4. Adds Pester tests to validate resource discovery
5. Adds logic to remove role assignment at subscription scope for service principal at cleanup
6. Changes the AzOpsPull operation, it performs a discovery which includes roles, policy's and resources to enable the extended tests
7. Fixes spelling output
N/A
Performed a full run of Pester tests resulting in successful deployment and discovery of resources at …
> Expanded Pester automated integration testing

- src/functions/Invoke-AzOpsPush.ps1
Expanded condition that was already in place for ARM templates to avoid creating duplicate deployment entries when submitting bicep templates with parameter files. 
Closing #504
> Condition to avoid duplicate bicep deployments using parameter files

- .github/linters/.markdown-lint.yml
- .github/workflows/super-linter.yml
- .github/workflows/tests.yml
- README.md
Added pipeline to use < https://github.com/github/super-linter>.
At this time it will only lint Markdown files, fixes #525
1. Adds GitHub Action "Lint Code Base"
2. Update README.md with status badge and some syntax errors found with super-linter
3. Update AzOps - Test to use OIDC
N/A
N/A
> Adding linting for Markdown files

- src/data/template/Microsoft.Authorization/policyAssignments.template.jq
Updated jq filter for policyAssignments to exclude Identities.UserManagedIdentity property when it is not being used. 
Also updated filter to change identity.IdentityType to Identity.Type
Closing #529. 
JQ filter validation done @ https://jqplay.org/s/FetEy603yQ
Successful test run from branch:
> Update jq filter for policyAssignments to exclude UMI and change IdentityType to Type

- src/functions/Initialize-AzOpsEnvironment.ps1
Added logic to fix lookup of root mg permissions when using managed identity. Issue introduced in latest Az.Accounts. 
Closing #533
**Before:**
**After:**
Also validated that regular user account as well as service principal works as before.
> Update logic to validate  mg permissions when using managed identity 

- src/data/template/Microsoft.Authorization/policyAssignments.template.jq
Update jq filter for policyAssignment with UMI. In this case
1) identity.PrincipalId and identity.TenantId are both null and can be removed
2) UserAssignedIdentities should only contain (according to validation error) "the resource exisiting property" (sic) so removing PrincipalId and ClientId from it
1. #538 
None identified.
I'm new to 'jq' and only tweaked the jq filter as such and did not rebuild the PowerShell module as a whole.
JQ filter validation done @ https://jqplay.org/s/kM2UYiFcvd
I expect some feedback on that jg logic... ;-)
> updated jq filter for policyAssignments with UMI

- src/functions/Initialize-AzOpsEnvironment.ps1
- src/internal/functions/Get-AzOpsCurrentPrincipal.ps1
- src/internal/functions/Remove-AzOpsDeployment.ps1
- src/localized/en-us/Strings.psd1
- src/tests/integration/Repository.Tests.ps1
Additional fix for #533 related to `Remove-AzOpsDeployment`. 
- Created separate function to determine current principaltype/principalId
- Updated `Initialize-AzOpsEnvironment` and `Remove-AzOpsDeployment` to leverage the new cmdlet
- Added integration test for resource deletion of `RoleAssignments` and `PolicyAssignments`
> Fix managed identity lookup in Remove-AzOpsDeployment

- .github/linters/.markdown-lint.yml
Added some exclusions to `.markdown-lint.yml`
1. Added `allowed_elements` to `MD033` to allow use of html tag <br/>
2. Added `MD034: true` to allow bare URLs. We need bare URLs to reference the AzOps-Accelerator repo in step-by-step guide.
N/A
N/A
> Added markdown linter exclusions

- src/internal/functions/New-AzOpsDeployment.ps1
- src/internal/functions/Remove-AzOpsDeployment.ps1
- src/internal/functions/Set-AzOpsWhatIfOutput.ps1
- src/localized/en-us/Strings.psd1
Expand error handling for WhatIf prediction failures as per #545. 
1. Expanded error handling for errors of type `DeploymentWhatIfResourceError`. 
2. Enriched/Contextualized WhatIf output with template file name to make it easier in case of multiple deployments in one PR
Test deployments for the prediction failure scenario: 
https://github.com/daltondhcp/azops-test00/pull/7
Test deployment for deletion with the enriched output: 
https://github.com/daltondhcp/azops-test00/pull/8
> Expand Validate/WhatIf deployment error handling for WhatIf prediction failures

- src/internal/functions/New-AzOpsScope.ps1
- src/localized/en-us/Strings.psd1
Investigated issue #257  was not able to reproduce -WhatIf failure.
This PR updates the message output of 'New-AzOpsScope -Path' by adjusts the string message content of 'New-AzOpsScope.Creating.FromFile' and setting 'ActionStringValues' as the other actions in New-AzOpsScope function.
Closing #257 with theses updated and harmonized message behaviors.
1. Changes New-AzOpsScope -Path message output
2. Changes AzOpsScope.Creating.FromFile string composition
N/A
Tested to create new scope's with -Path with the new message output.
> New-AzOpsScope Strings Update

- src/internal/functions/Get-AzOpsCurrentPrincipal.ps1
Bugfix in Get-AzOpsCurrentPrincipal to enable lookup of federated credentials/AccountType `ClientAssertion` causing thed pipeline to fail.
N/A
**Before change:** 
**After change:**
> Bugfix in Get-AzOpsCurrentPrincipal to handle federated credentials

- docs/wiki/Azure-Pipelines.md
Add a line to the setup script for Azure Pipelines to set the `main` branch as default
1. Setup script now sets main branch as default
Closes #611
> Set `main` as default branch in Azure DevOps

- src/internal/functions/Get-AzOpsManagementGroups.ps1
Update to `Get-AzOpsManagementGroups`  that fixes breaking change from Az.Resources 6.0.0 causing pipelines configured with `Core.PartialMgDiscoveryRoot` to fail. 
Closes #639 
N/A
✅ Validated [Pull](https://github.com/daltondhcp/azops-test00/actions/runs/2379856406), [Push](https://github.com/daltondhcp/azops-test00/actions/runs/2379925973) and [Validate](https://github.com/daltondhcp/azops-test00/actions/runs/2379895607) pipelines in environment that was previously failing 
**Output  Az.Resources < 6.0.0:**
**Output after Az.Resources 6.0.0**
> Fix issue in `Get-AzManagementGroups` causing partial discovery to fail 🚑 🚑 🚑 

- .gitignore
- src/tests/functional/Functional.Tests.ps1
- src/tests/integration/Repository.Tests.ps1
- src/tests/templates/azuredeploy.jsonc
This PR extends the automated integration testing to include a situation where the `Core.PartialMgDiscoveryRoot` setting is configured, allowing us to avoid a similar situation as with release of 1.8.0 #639.
This closes #641 
1.  changes integration test flow
2.  changes gitignore
N/A
Testing is automated and will be run as part of PR validation.
> Adding Automated testing for Core.PartialMgDiscoveryRoot

- src/internal/functions/New-AzOpsDeployment.ps1
- src/internal/functions/Remove-AzOpsDeployment.ps1
- src/internal/functions/Set-AzOpsWhatIfOutput.ps1
- src/localized/en-us/Strings.psd1
- src/tests/functional/Microsoft.Authorization/policyAssignments/scenario.ps1
- src/tests/functional/Microsoft.Authorization/roleAssignments/scenario.ps1
- src/tests/functional/Microsoft.Authorization/roleEligibilityScheduleRequests/scenario.ps1
- src/tests/functional/Microsoft.KeyVault/vaults/scenario.ps1
- src/tests/functional/Microsoft.Management/managementGroups/scenario.ps1
- src/tests/functional/Microsoft.Network/azureFirewalls/scenario.ps1
- src/tests/functional/Microsoft.Network/networkInterfaces/scenario.ps1
- src/tests/functional/Microsoft.Network/networkSecurityGroups/scenario.ps1
- src/tests/functional/Microsoft.Network/publicIPAddresses/scenario.ps1
- src/tests/functional/Microsoft.Network/routeTables/scenario.ps1
- src/tests/functional/Microsoft.Network/virtualNetworks/scenario.ps1
- src/tests/functional/Microsoft.Resources/resourceGroups/scenario.ps1
- src/tests/functional/Microsoft.Storage/storageAccounts/scenario.ps1
- src/tests/functional/Microsoft.Web/serverfarms/scenario.ps1
- src/tests/functional/Microsoft.Web/sites/scenario.ps1
This PR fixes #652 
As the issue describes current character limit does not correctly take into account all character aspects.
Logic is updated to take existing content into account and also produce warnings at runtime when maximum is reached.
1. Fixes Set-AzOpsWhatIfOutput.ps1
2. Changes New-AzOpsDeployment.ps1
3. Changes Remove-AzOpsDeployment.ps1
4. Changes Strings.psd1
N/A
Entire PR within limits:
Parts of PR within limits:
> Set-AzOpsWhatIfOutput limit calc update

- src/internal/functions/Get-AzOpsResourceDefinition.ps1
- src/internal/functions/Set-AzOpsWhatIfOutput.ps1
- src/tests/functional/Microsoft.Insights/activityLogAlerts/deploy/deploy.json
- src/tests/templates/azuredeploy.jsonc
Harmonize temporary files output location by querying runtime environment for location.
Closes #678
1. Adjust Get-AzOpsResourceDefinition.ps1 temporary export path
2. Adjust Set-AzOpsWhatIfOutput.ps1 export path
1. N/A
Testing has been performed on Linux and Windows runtime environment without errors.
> Generalize Temp Pathing

- src/AzOps.psd1
- src/internal/classes/AzOpsScope.ps1
- src/tests/templates/azuredeploy.jsonc
- Fix issue where management groups with the same displayName didn't pull successfully. 
Removed all references to displayName in logic. 
- Bump PSFramework version 
N/A
Verified in environment that previously failed. Tests should ensure no new issues have been introduced with these changes.
> Ensure management group name uniqueness

- src/internal/functions/Get-AzOpsResourceDefinition.ps1
- src/localized/en-us/Strings.psd1
Partially adressing #699, specifically the RP-errors from the export API. 
Tested in my own demo environment successfuly. 
Test coverage for the scenarios in place. In case the specific child resources in the test cases are not exported due to RP issues, tests will obviously fail ❌ 
- [X} Performed testing and provided evidence.
> Added graceful error handling for child resource export

- .github/workflows/dependencies.yml
- .github/workflows/release.yml
- .github/workflows/super-linter.yml
- .github/workflows/tests.yml
- .github/workflows/wiki-sync.yml
- docs/wiki/Self-Hosted.md
This PR updates dependant checkout action from v2 to v3 to keep with the times [Node 12 out of support](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).
1. Changes all workflows to `actions/checkout@v3` from `actions/checkout@v2`
N/A
N/A
> Update to actions/checkout@v3

- src/internal/functions/Get-AzOpsResourceDefinition.ps1
This PR closes #697 by adding support for wildcard in setting `Azops.Core.IncludeResourcesInResourceGroup`.
1. Changes `Get-AzOpsResourceDefinition.ps1`
1. n/a
Tested in my own environment with 100+ subscriptions using wildcard like `*` and `rg-name-*`.
Also tried the pester tests, but a bit unsure if we should add anything there or not for this setting. The docs/wiki might still be good as is.
> Add support for wildcard in setting Azops.Core.IncludeResourcesInResourceGroup

- docs/wiki/Prerequisites.md
- src/functions/Invoke-AzOpsPull.ps1
- src/localized/en-us/Strings.psd1
Remove `Directory Readers` Azure AD role requirement for `roleAssignments`. Warning message and docs changed to reflect new behavior. 
Closing #722 
N/A
Tested in my own environment and can confirm that roleAssignments are pulled back without Directory Reader permissions.
> Remove `Directory Readers` Azure AD role requirement for `roleAssignments` pull 

- src/functions/Invoke-AzOpsPush.ps1
- src/internal/classes/AzOpsScope.ps1
- src/internal/functions/ConvertFrom-AzOpsBicepTemplate.ps1
- src/localized/en-us/Strings.psd1
- Updated logic to solve #730
- Broken out bicep conversion into separate function to minimize duplicate code 
- Added logic to validate parameter schema and remove undesired warning #717 
N/A
- Tested to push/deploy only a parameter file with a corresponding bicep templates with successful results. Prior to change it was failing as per issue. 
- Verified that undesired warning is not showing when a valid parameter file is used. 
Tests cover all other cases.
> Bicep deployment fix for parameter file updates

- docs/wiki/GitHub-Actions.md
Github Command to set can_approve_pull_request_reviews should have upper case -F instead of -f
1. docs\wiki\GitHub-Actions.md
N/A
Please see issue #732 
- [x ] Checked for duplicate [Pull Requests](https://github.com/Azure/azops/pulls)
> Minor correction to Github Command

- src/internal/functions/Get-AzOpsPolicy.ps1
This PR changes nested resource apiVersion returned by `Az.ResourceGraph` specifically for  `DINE` to remove unwanted information.
1. Get-AzOpsPolicy.ps1
N/A
Pull and Push operation of DINE policy with resources tested.
> Patch apiVersion on nested microsoft.authorization/policydefinitions resources

- src/internal/functions/ConvertFrom-AzOpsBicepTemplate.ps1
- src/localized/en-us/Strings.psd1
- src/tests/integration/Repository.Tests.ps1
- src/tests/templates/biceperror.bicep
Throw exception on failing bicep build.
Updated logic to solve: https://github.com/Azure/AzOps/issues/767
Added check in ConvertFrom-AzOpsBicepTemplate to see if the bicep build command was able to create its output file as a result of the bicep build command.
Without this, the exception is swallowed in validate/push pipelines.
1. adds exception if bicep build failed, and no transpiled file was created
N/A
Tested if exception was throwed when it was required, automated test case added to catch code regression.
> Throw exception on failing bicep build

- docs/wiki/Frequently-Asked-Questions.md
- docs/wiki/Self-Hosted.md
- src/functions/Initialize-AzOpsEnvironment.ps1
- src/functions/Invoke-AzOpsPush.ps1
- src/localized/en-us/Strings.psd1
This PR fixes #754 
- Adds Logic in `Invoke-AzOpsPush` to check for temporary lingering files from previous executions and removes them.
- Adds Guidance in Wiki FAQ about temporary files.
- Adds Self-Hosted section when multiple agents/runners co-exists on the same compute resource.
1.  Changes `Frequently-Asked-Questions.md`
2.  Changes `Self-Hosted.md`
3.  Changes `Invoke-AzOpsPush.ps1`
4. Changes `Strings.psd1`
N/A
Removal logic has been tested and files are removed successfully.
> Adding Removal of Lingering Files

- src/data/template/Microsoft.Authorization/policyAssignments.jq
- src/tests/integration/Repository.Tests.ps1
- src/tests/templates/policywithuam.bicep
This PR adds logic that was fixed back in `1.7.2` #538 , but was regressed in `2.0.0` affecting deployability of policy assignments with userAssignedIdentities. It also contains automated testing to catch similar regressions moving forward.
1. Changes `policyAssignments.jq`
2. Changes `Repository.Tests.ps1`
3. Adds `policywithuam.bicep`
N/A
Testing is included in automated pr validation.
> Fix regression of #538

- .github/workflows/tests.yml
- scripts/Remove-AzOpsTestsDeployment.ps1
- src/data/template/Microsoft.Subscription/subscriptions.template.jq
- src/functions/Invoke-AzOpsPull.ps1
- src/internal/functions/ConvertTo-AzOpsState.ps1
- src/tests/Pester.ps1
- src/tests/integration/Repository.Tests.ps1
- src/tests/subscriptiononly/SubOnly.Tests.ps1
- src/tests/templates/rgsubonlydeploy.bicep
- src/tests/templates/rgsubonlydeploy.parameters.json
- src/tests/templates/stasubonlydeploy.bicep
This PR fixes #775 by modifying logic to manage **Subscription Only Discovery**, this was regressed in `2.0.0` affecting deployment of objects at and below Subscription scope.
The PR also contains expanded automated testing that adds another GitHub Action Job to catch similar regressions moving forward.
1. Changes `tests.yml`
2. Changes `Remove-AzOpsTestsDeployment.ps1`
3. Adds `Microsoft.Subscription/subscriptions.template.jq`
4. Changes `Invoke-AzOpsPull.ps1`
5. Changes `ConvertTo-AzOpsState.ps1`
6. Changes `Pester.ps1`
7. Changes `Repository.Tests.ps1`
8. Adds `SubOnly.Tests.ps1`
9. Adds `rgsubonlydeploy.bicep`
10. Adds `rgsubonlydeploy.parameters.json`
11. Adds `stasubonlydeploy.bicep`
N/A
Testing has been performed in test environment, for future PR's its included in automated pr …
> Fix regression of Subscription Only Discovery with no Management Group

- docs/wiki/Azure-Pipelines.md
Update script in wiki to use ADOPS PowerShell module.
Fixes #750 
Fixes #753
1. Update wiki documentation for Azure Pipelines setup
Ran code to create a new Project, repository, pipelines, variable groups, settings and policies. Tested running the push pipeline which ran successfully.
> Update ADO Pipeline instructions

- docs/wiki/Azure-Pipelines.md
This PR includes minor changes to the Azure DevOps install script in the Wiki to mirror the 2.0.2 minor update of the required ADOPS module.
Closes #824
> Update AzDO Installscript

- src/internal/functions/New-AzOpsDeployment.ps1
- src/internal/functions/Set-AzOpsContext.ps1
- src/tests/integration/Repository.Tests.ps1
Suggested fix for #853 
This PR makes sure no output is caught from `Set-AzContext`.
> Silence output from Set-AzOpsContext

- scripts/UpdateRequiredModules.ps1
- src/internal/functions/Assert-AzOpsJqDependency.ps1
- src/tests/functional/Microsoft.Network/connections/deploy/deploy.json
This PR closes #865 by changing the logic used to determine jq --version output.
1. Changes Assert-AzOpsJqDependency.ps1
1. N/A
Testing with a jq version variable set to 1.7.1 evaluates correct.
> Fix jq version evaluation

- src/functions/Invoke-AzOpsPush.ps1
- src/internal/functions/New-AzOpsDeployment.ps1
This PR changes how AzOps utilizes the template file during deployment and fixes #868.
**New behavior:**
New-AzOpsDeployment will first attempt to utilize a parameter $TemplateObject that contains the relevant template content as a hashtable. Only if this parameter $TemplateObject is missing will it attempt to read the template file content.
**Current behavior:**
New-AzOpsDeployment attempt to read the content of the template file and potentially lock it during read and deployment.
1. Changes `Invoke-AzOpsPush.ps1`
2. Changes `New-AzOpsDeployment.ps1`
1. N/A
Tests have been performed that locks the template files destined for deployment prior to `Invoke-AzOpsPush` calls `New-AzOpsDeployment` and with this code change the module continues to execute successful deployments. Without the code …
> Load Template Content for Push Deployment in-memory

- src/data/template/Microsoft.Authorization/policyDefinitions.jq
- src/data/template/Microsoft.Authorization/policySetDefinitions.jq
This PR fixes #874 by adjusting `policyDefinitions.jq` and `policySetDefinitions.jq` to allow `defaultValue` to be empty.
1. Changes `policyDefinitions.jq`
2. Changes `policySetDefinitions.jq`
N/A
Tests have been performed to evaluate if empty `defaultValue` is pulled back and persisted while still removing other unwanted empty key value pairs.
> Fix Jq filter to allow empty defaultValue for policy definition and set definition

- src/functions/Invoke-AzOpsPush.ps1
- src/internal/functions/ConvertFrom-AzOpsBicepTemplate.ps1
- src/localized/en-us/Strings.psd1
This PR fixes #879 and similar patterns.
With this changed logic the module will check that whenever deployment jobs are constructed example: `baseTemplate` + `parameterTemplate` it will check that neither file is being deleted in the same push to the module. If there in an overlap the file targeted for deletion will be skipped when constructing deployment jobs.
Without this logic the module based on its current order of processing would unintentionally first re-process (deploy) the deleted file before proceeding with deletion.
1. Changes `Invoke-AzOpsPush.ps1`
2. Changes `ConvertFrom-AzOpsBicepTemplate.ps1`
3. Changes `Strings.psd1`
N/A
Tests have been performed with the following combinations using both `.json, parameters.json, bicep, bicepparams`:
- Changes to `baseTemplate` and …
> Fix File Pair Processing of Modify and Deletion Overlap

- src/functions/Invoke-AzOpsPush.ps1
- src/tests/integration/Repository.Tests.ps1
- src/tests/templates/decoy.westeurope.bicep
- src/tests/templates/decoy.westeurope.x123.parameters.json
- src/tests/templates/deployallrt.westeurope.bicep
- src/tests/templates/deployallrt.westeurope.x123.parameters.json
- src/tests/templates/deployallrt.westeurope.xabc.bicepparam
- src/tests/templates/deployallrt2.westeurope.bicep
This PR changes two key pieces to fix #886 and avoid incorrect recursive parameter discovery.
1. Adjusts how the `$deploymentName` is derived at run-time. Ensuring that if the deployment job que contains overlapping deployments, we only process it once when they have matching deployment name and files.
1. Addressing #886
2. During recursive parameter discovery there was a possibility that a un-related file pair would have been discovered and queued for processing. This is not the intent so a step in the recursive process has been added to regex match the base name of any discovered files prior to any further processing.
1. Changes `Invoke-AzOpsPush.ps1`
4. Changes `Repository.Tests.ps1`
5. Adds `decoy.westeurope.bicep`
6. Adds `decoy.westeurope.x123.parameters.json`
7. Adds …
> Fix Duplicate conflicting deployments with DeployAllMultipleTemplateParameterFiles

- src/internal/functions/Get-AzOpsResource.ps1
- src/localized/en-us/Strings.psd1
This PR adds `Try` and `Catch` logic  to `Get-AzOpsResource.ps1` to manage underlying `Az.PowerShell` changes in error handling.
Without this code change the module can throw during custom resource deletion `$scriptCmd = {& $wrappedCmd @PSBoundParameters}` due to -ErrorAction handling changes in depended modules.
1. Changes `Get-AzOpsResource.ps1`
2. Changes `Strings.psd1`
1. N/A
Deployment and deletion of custom resources have been tested.
> Fix Resource Existence Validation Error Logic

- docs/wiki/Frequently-Asked-Questions.md
- src/functions/Initialize-AzOpsEnvironment.ps1
- src/functions/Invoke-AzOpsPush.ps1
- src/internal/functions/ConvertTo-AzOpsState.ps1
- src/internal/functions/Get-AzOpsResourceDefinition.ps1
- src/internal/functions/Save-AzOpsManagementGroupChild.ps1
- src/localized/en-us/Strings.psd1
This PR adds logic to compare the API version returned for a Resource Provider (RP) with the API version returned by the Graph service. By doing this and overriding the RP `apiVersion` if it does not match Graph `apiVersion` while still being listed as a functional `apiVersion` by the RP ensures a consistent pull experience and fix #911.
When running module in debug mode each time an `apiVersion` override is performed the following message is emitted.
1. Changes `Initialize-AzOpsEnvironment.ps1`
2. Changes `Invoke-AzOpsPush.ps1`
3. Changes `ConvertTo-AzOpsState.ps1`
4. Changes `Get-AzOpsResourceDefinition.ps1`
5. Changes `Save-AzOpsManagementGroupChild.ps1`
6. Changes `Strings.psd1`
N/A
Different performance and manual testing have been performed to ensure override functionally does not …
> Update ApiVersion Logic to compare RP with Graph

- src/internal/functions/Remove-AzOpsDeployment.ps1
This PR fixes the erroneous handling of `Microsoft.Authorization/roleAssignments` deletions that was introduced in `AzOps 2.6.5` causing validate and push to fail when the roleAssignments had been removed out of bound.
This fixes #921.
1. Changes `Remove-AzOpsDeployment.ps1`
N/A
With new logic validate does not fail:
With new logic push does not fail:
> Fix Regression of Role Assignment Deletion Logic

- src/internal/functions/Get-AzOpsResourceDefinition.ps1
- src/localized/en-us/Strings.psd1
This PR addresses issue #932 by improving error messages during child resource export.
- Added resource group export parameters to error messages to provide relevant troubleshooting insights.
- Updated processing logic to prevent unintentional handling of resources that are not associated with a resource group during export.
1.  Changes `Get-AzOpsResourceDefinition.ps1`
2. Changes `Strings.psd1`
1. N/A
Utilize automated testing from GH action.
> Fix issues with child resource export error verbosity and processing of resource with null or empty resource group
